### ISSUE TITLE
examples do not work on IE

### ISSUE THREAD

**Issue by reiern70** [wicketstuff/wiquery-jqplot#1]
Examples do not work on IE. I guess some canvas emulating JavaScript library (excanvas.js?) should be missing.

Thanks for your nice work!

Ernesto

**Comment by hielkehoeve** [comment]
Will look into it. We never use Internet Explorer ourselves so issues like these are very helpful.

**Comment by reiern70** [comment]
Thanks Hielke! I guess it will be fixed by conditionally including excanvas.js if request comes form IE.

1-http://www.jqplot.com/docs/files/usage-txt.html

**Comment by hielkehoeve** [comment]
Issue solved (in 3 commits, windows command-line git isn't the best one around).

**Comment by reiern70** [comment]
Thanks!

**Comment by hielkehoeve** [comment]
Added a tweaks to the fix. IE9 seems to have canvas support, so we only include excanvas.js when IE and major version < 9.
