### ISSUE TITLE
no directed support for date based charts

### ISSUE THREAD

**Issue by reiern70** [wicketstuff/wiquery-jqplot#2]
I have added direct support for Date based series on fork/branch

1-https://github.com/reiern70/wiquery-jqplot/blob/datetime_plugincontribution/src/main/java/nl/topicus/wqplot/data/DateNumberSeries.java
2-https://github.com/reiern70/wiquery-jqplot/blob/datetime_plugincontribution/src/main/java/nl/topicus/wqplot/data/DateNumberSeriesEntry.java

**Comment by hielkehoeve** [comment]
Best is to give me a pull request so I can pull your commit into my branch.

**Comment by reiern70** [comment]
done

https://github.com/hielkehoeve/wiquery-jqplot/pull/5
