### ISSUE TITLE
puglins hardcoded on JQPlot class

### ISSUE THREAD

**Issue by reiern70** [wicketstuff/wiquery-jqplot#3]
Right now plugins are hardcoded on class JQPlot.java I have added some machinery that allows to make this extensible. Details can be found at branch.

https://github.com/reiern70/wiquery-jqplot/blob/datetime_plugincontribution

**Comment by hielkehoeve** [comment]
merged your code into master, did see some possible tweaks. But overall a good idea!!

**Comment by reiern70** [comment]
Hielke,

Thanks for looking into my changes. Yes, the thing can surely be improved... what I wanted was to have a way to register new plugins or plugin contributors.

I will start using your project for a project I'm working at right now so I might come back with further additions. It is OK to put them on new branches? Or shall I submit patches?

By the way thanks to you and Topicus for sharing your code:-)  

Best,

Ernesto

**Comment by hielkehoeve** [comment]
Which ever you want, branches are just as easy to merge as patch files. Might be easier for you as well.
Hope you enjoy it as much as we do.
